export const userRank = [
  { rank: 1, name: '김하늘', region: '서울특별시 강북구', organization: '서울환경청', score: 982 },
  {
    rank: 2,
    name: '박지우',
    region: '대전광역시 유성구',
    organization: '대전그린센터',
    score: 964,
  },
  { rank: 3, name: '이준호', region: '경기도 성남시', organization: '경기에코시티', score: 957 },
  {
    rank: 4,
    name: '최서윤',
    region: '부산광역시 해운대구',
    organization: '부산지속가능연구소',
    score: 951,
  },
  { rank: 5, name: '정민규', region: '전라북도 전주시', organization: '전북지속협', score: 946 },
  {
    rank: 6,
    name: '한예린',
    region: '대구광역시 수성구',
    organization: '대구푸른환경회',
    score: 933,
  },
  {
    rank: 7,
    name: '오세훈',
    region: '인천광역시 연수구',
    organization: '인천에코네트워크',
    score: 921,
  },
  {
    rank: 8,
    name: '윤다연',
    region: '강원특별자치도 원주시',
    organization: '원주지속협',
    score: 910,
  },
  {
    rank: 9,
    name: '조민재',
    region: '충청남도 천안시',
    organization: '충남그린시민단',
    score: 899,
  },
  {
    rank: 10,
    name: '김지안',
    region: '전라남도 순천시',
    organization: '순천지속가능센터',
    score: 893,
  },
  {
    rank: 11,
    name: '배진수',
    region: '서울특별시 종로구',
    organization: '종로환경모임',
    score: 887,
  },
  { rank: 12, name: '송가람', region: '울산광역시 남구', organization: '울산그린클럽', score: 875 },
  { rank: 13, name: '장우석', region: '충청북도 청주시', organization: '청주에코맘', score: 869 },
  { rank: 14, name: '임하윤', region: '경기도 고양시', organization: '성남환경지킴이', score: 860 },
  {
    rank: 15,
    name: '김유진',
    region: '제주특별자치도 제주시',
    organization: '제주생태연구소',
    score: 854,
  },
  { rank: 16, name: '전예빈', region: '광주광역시 북구', organization: '광주녹색회', score: 843 },
  {
    rank: 17,
    name: '이도현',
    region: '세종특별자치시 도담동',
    organization: '세종지속협',
    score: 832,
  },
  { rank: 18, name: '유하늘', region: '경상북도 경주시', organization: '경주에코가든', score: 827 },
  { rank: 19, name: '하승민', region: '경상남도 창원시', organization: '창원그린살롱', score: 812 },
  {
    rank: 20,
    name: '강주원',
    region: '서울특별시 마포구',
    organization: '마포환경교육센터',
    score: 799,
  },
]

export const regionRank = [
  { rank: 1, region: '서울특별시 강북구', score: 953 },
  { rank: 2, region: '경기도 성남시', score: 941 },
  { rank: 3, region: '부산광역시 해운대구', score: 932 },
  { rank: 4, region: '인천광역시 연수구', score: 918 },
  { rank: 5, region: '대전광역시 유성구', score: 905 },
  { rank: 6, region: '전라북도 전주시', score: 897 },
  { rank: 7, region: '충청남도 천안시', score: 888 },
  { rank: 8, region: '광주광역시 북구', score: 872 },
  { rank: 9, region: '전라남도 순천시', score: 864 },
  { rank: 10, region: '충청북도 청주시', score: 853 },
  { rank: 11, region: '대구광역시 수성구', score: 839 },
  { rank: 12, region: '경상북도 포항시', score: 826 },
  { rank: 13, region: '경상남도 창원시', score: 814 },
  { rank: 14, region: '강원특별자치도 원주시', score: 799 },
  { rank: 15, region: '울산광역시 남구', score: 788 },
  { rank: 16, region: '세종특별자치시 도담동', score: 775 },
  { rank: 17, region: '제주특별자치도 제주시', score: 761 },
]
